### PR TITLE
DeprecationWarning: PY_SSIZE_T_CLEAN #13

### PR DESCRIPTION
**Pull request by vadimszzz**

### CODE REVIEW

**Comment by vadimszzz** [comment]
@samuelcolvin

**Comment by vadimszzz** [comment]
@samuelcolvin

**Comment by vadimszzz** [comment]
@samuelcolvin

**Comment by vadimszzz** [comment]
@samuelcolvin

**Comment by vadimszzz** [comment]
@samuelcolvin

**Comment by vadimszzz** [comment]
@samuelcolvin It's 2022 now, fix xdelta3 fail

**Comment by vadimszzz** [comment]
@samuelcolvin transfer ownership of the repository and pip project to me please if you don't want to maintain it

**Comment by samuelcolvin** [comment]
This is no way to speak to people in the open source community.

I'll try to fix this soon, but we need to setup GitHub actions.

I won't be transferring the repo to you.

**Comment by liiight** [comment]
> @samuelcolvin transfer ownership of the repository and pip project to me please if you don't want to maintain it

As someone who is in no way affiliated with this project and is a very satisfied user of it I just want to say STFU you asshole. 

@samuelcolvin consider this my contribution

**Comment by samuelcolvin** [comment]
After considering this, I'm not going to fix this bug, but instead mark this repo as archived.

Reasons:
* This project has not seen mass adoption - I believe there are more effective ways to use my time on open source
* I'm not knowledgeable enough about c to maintain it reliably

**Pull request closed without merging**
